import { Category, Equipment, Exercise, Force, Level, Mechanic, Muscle } from "@prisma/client";

const seedDataNames: string[] = [
  "Deadlift",
  "Pull-Up",
  "Bench Press",
  "Lunge",
  "Plank",
  "Squat",
  "Push-Up",
  "Russian Twist",
  "Burpee",
  "Mountain Climber",
  "Dumbbell Shoulder Press",
  "Kettlebell Swing",
  "Romanian Deadlift",
  "Barbell Hip Thrust",
  "Box Jump",
  "Dumbbell Bent-Over Row",
  "Jumping Lunges",
  "Incline Dumbbell Bench Press",
  "Russian Kettlebell Swing",
  "Overhead Press",
  "Hanging Leg Raise",
  "Step-Up",
  "Plank Jacks",
  "Dumbbell Front Squat",
  "Dumbbell Lateral Raise",
  "Dumbbell Bicep Curl",
  "Dumbbell Shoulder Press",
  "Barbell Squat",
  "Barbell Deadlift",
  "Barbell Bench Press",
  "Barbell Row",
  "Barbell Overhead Press",
  "Barbell Curl",
  "Barbell Tricep Extension",
  "Barbell Lunges",
  "Barbell Hip Thrust",
  "Barbell Romanian Deadlift",
  "Barbell Shoulder Press",
  "Barbell Shrug",
  "Barbell Upright Row",
  "Barbell Front Raise",
  "Barbell Calf Raise",
  "Dumbbell Squat",
  "Dumbbell Deadlift",
  "Dumbbell Bench Press",
  "Dumbbell Row",
  "Dumbbell Overhead Press",
  "Dumbbell Curl",
  "Dumbbell Tricep Extension",
  "Dumbbell Lunges",
  "Dumbbell Step-Up",
  "Dumbbell Calf Raise",
  "Dumbbell Flyes",
  "Dumbbell Reverse Flyes",
  "Dumbbell Hammer Curl",
  "Dumbbell Tricep Kickback",
  "Dumbbell Side Lateral Raise",
  "Dumbbell Front Raise",
  "Cable Flyes",
  "Cable Row",
  "Cable Lat Pulldown",
  "Cable Crossover",
  "Cable Bicep Curl",
  "Cable Tricep Pushdown",
  "Cable Crunch",
  "Cable Side Lateral Raise",
  "Cable Front Raise",
  "Leg Press",
  "Leg Extension",
  "Leg Curl",
  "Calf Raise",
  "Smith Machine Squat",
  "Smith Machine Bench Press",
  "Smith Machine Lunges",
  "Smith Machine Shoulder Press",
  "Smith Machine Romanian Deadlift",
  "Treadmill Running",
  "Stationary Bike",
  "Elliptical Machine",
  "Rowing Machine",
  "Stair Climber",
  "Jump Rope",
  "Swimming",
  "HIIT (High-Intensity Interval Training)",
  "Circuit Training",
  "Yoga",
  "Pilates",
  "Zumba",
  "Kickboxing",
  "Martial Arts (such as karate, taekwondo, or jiu-jitsu)"
];

const seedData: Omit<Exercise, 'id'>[] = [
  {
    name: "Deadlift",
    aliases: [],
    primaryMuscles: [Muscle.HAMSTRINGS, Muscle.GLUTES, Muscle.BACK],
    secondaryMuscles: [Muscle.QUADRICEPS, Muscle.FOREARMS],
    force: Force.PULL,
    level: Level.INTERMEDIATE,
    mechanic: Mechanic.COMPOUND,
    equipment: [Equipment.BARBELL],
    category: [Category.STRENGTH, Category.POWERLIFTING],
    instructions: ["Stand with your feet hip-width apart and the barbell over your mid-foot.", "Bend at the hips and knees to grip the bar.", "Keep your back straight and pull the weight up off the floor.", "Lower the weight back down under control."],
    description: "The deadlift is a weight training exercise in which a loaded barbell is lifted off the ground to the level of the hips, and then lowered to the ground again.",
    tips: ["Keep your back straight and your core engaged throughout the movement.", "Use your leg and hip strength to lift the bar.", "Avoid rounding your back or lifting with your lower back."]
  },
  {
    name: "Pull-Up",
    aliases: [],
    primaryMuscles: [Muscle.LATS, Muscle.BICEPS],
    secondaryMuscles: [Muscle.BACK, Muscle.SHOULDERS],
    force: Force.PULL,
    level: Level.INTERMEDIATE,
    mechanic: Mechanic.COMPOUND,
    equipment: [Equipment.PULL_UP_BAR],
    category: [Category.CALISTHENICS],
    instructions: ["Grip the bar with your hands shoulder-width apart.", "Hang with your arms fully extended.", "Pull your body up until your chin is over the bar.", "Lower yourself back down to the starting position."],
    description: "The pull-up is a strength training exercise for the upper body, particularly the back and biceps.",
    tips: ["Avoid using momentum to pull yourself up.", "Pull your elbows down and back, keeping them close to your body.", "Focus on squeezing your back muscles at the top of the movement."]
  },
  {
    name: "Bench Press",
    aliases: [],
    primaryMuscles: [Muscle.CHEST, Muscle.TRICEPS],
    secondaryMuscles: [Muscle.SHOULDERS],
    force: Force.PUSH,
    level: Level.BEGINNER,
    mechanic: Mechanic.COMPOUND,
    equipment: [Equipment.BARBELL],
    category: [Category.STRENGTH, Category.POWERLIFTING],
    instructions: ["Lie back on a flat bench with a barbell in the rack above you.", "Grip the bar with hands slightly wider than shoulder-width apart.", "Lower the bar to your chest.", "Press the bar back up to the starting position."],
    description: "The bench press is a compound exercise that primarily targets the chest, triceps, and front deltoids.",
    tips: ["Keep your feet flat on the ground and your back flat against the bench.", "Avoid arching your back or lifting your hips off the bench.", "Control the weight as you lower it to your chest and press it back up."]
  },
  {
    name: "Lunge",
    aliases: [],
    primaryMuscles: [Muscle.QUADRICEPS, Muscle.GLUTES, Muscle.HAMSTRINGS],
    secondaryMuscles: [Muscle.CALVES],
    force: Force.PUSH,
    level: Level.BEGINNER,
    mechanic: Mechanic.COMPOUND,
    equipment: [Equipment.BODYWEIGHT, Equipment.DUMBBELL, Equipment.KETTLEBELL],
    category: [Category.STRENGTH],
    instructions: ["Stand tall with feet hip-width apart.", "Take a big step forward with one foot.", "Lower your body until your front knee is at a 90-degree angle.", "Push off your front foot to return to the starting position."],
    description: "The lunge is a great functional exercise to use in warming up or as a staple in your lower-body routine.",
    tips: ["Keep your torso straight and your eyes facing forward.", "Avoid letting your knee extend past your toes.", "Keep your weight evenly distributed between both legs."]
  },
  {
    name: "Plank",
    aliases: [],
    primaryMuscles: [Muscle.CORE],
    secondaryMuscles: [Muscle.GLUTES, Muscle.SHOULDERS],
    force: Force.STATIC,
    level: Level.BEGINNER,
    mechanic: Mechanic.ISOLATION,
    equipment: [Equipment.BODYWEIGHT],
    category: [Category.STRENGTH],
    instructions: ["Get into a pushup position.", "Bend your elbows and rest your weight on your forearms.", "Hold this position, maintaining a straight line from head to feet."],
    description: "The plank is a core strength exercise that involves maintaining a position similar to a push-up for the maximum possible time.",
    tips: ["Engage your core and squeeze your glutes.", "Avoid letting your hips sag or your back arch.", "Keep your neck and spine neutral by looking at a spot on the floor ahead of your hands."]
  },
  {
    name: "Squat",
    aliases: [],
    primaryMuscles: ["QUADRICEPS", "GLUTES", "HAMSTRINGS"],
    secondaryMuscles: ["CALVES"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["BARBELL"],
    category: ["STRENGTH"],
    instructions: [
      "Stand with your feet shoulder-width apart and the barbell resting on your upper back.",
      "Bend at the knees and hips to lower your body into a squat position.",
      "Keep your chest up and your back straight.",
      "Push through your heels to return to the starting position."
    ],
    description: "The squat is a compound exercise that targets the muscles of the lower body, including the quadriceps, glutes, and hamstrings.",
    tips: [
      "Maintain proper form throughout the movement, keeping your knees in line with your toes.",
      "Engage your core for stability.",
      "Start with lighter weights and gradually increase as you gain strength."
    ]
  },
  {
    name: "Push-Up",
    aliases: [],
    primaryMuscles: ["CHEST", "TRICEPS"],
    secondaryMuscles: ["SHOULDERS", "CORE"],
    force: "PUSH",
    level: "BEGINNER",
    mechanic: "COMPOUND",
    equipment: ["BODYWEIGHT"],
    category: ["CALISTHENICS"],
    instructions: [
      "Start in a high plank position with your hands slightly wider than shoulder-width apart.",
      "Lower your body until your chest nearly touches the ground.",
      "Push through your hands to return to the starting position."
    ],
    description: "The push-up is a classic bodyweight exercise that targets the muscles of the upper body, including the chest, triceps, and shoulders.",
    tips: [
      "Maintain a straight line from head to heels throughout the movement.",
      "Engage your core and keep your glutes tight.",
      "Modify the exercise by performing it on your knees if needed."
    ]
  },
  {
    name: "Russian Twist",
    aliases: [],
    primaryMuscles: ["CORE", "OBLIQUES"],
    secondaryMuscles: ["HIP_FLEXORS"],
    force: "ROTATION",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["BODYWEIGHT"],
    category: ["CORE"],
    instructions: [
      "Sit on the ground with your knees bent and your feet off the floor.",
      "Lean back slightly while keeping your back straight.",
      "Twist your torso to the right side, bringing your hands or a weight to the floor.",
      "Twist your torso to the left side, bringing your hands or a weight to the floor."
    ],
    description: "The Russian Twist is an exercise that targets the core and oblique muscles, helping to improve rotational strength and stability.",
    tips: [
      "Engage your core throughout the exercise.",
      "Maintain a straight back and avoid rounding your shoulders.",
      "Start with lighter weights or no weights and progress as you become more comfortable with the movement."
    ]
  },
  {
    name: "Burpee",
    aliases: [],
    primaryMuscles: ["FULL_BODY"],
    secondaryMuscles: ["CALVES", "BACK", "HIP_FLEXORS", "FOREARMS"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["BODYWEIGHT"],
    category: ["CARDIO", "FULL_BODY"],
    instructions: [
      "Start in a standing position with your feet shoulder-width apart.",
      "Squat down and place your hands on the floor in front of you.",
      "Kick your feet back to a high plank position.",
      "Jump your feet forward and return to the squat position.",
      "Jump up explosively with your hands reaching overhead."
    ],
    description: "The burpee is a full-body exercise that combines elements of strength, cardiovascular endurance, and explosive power.",
    tips: [
      "Maintain proper form throughout the movement, keeping your back straight and your core engaged.",
      "Focus on landing softly when jumping back and forth.",
      "Modify the exercise by stepping back and forward instead of jumping if needed."
    ]
  },
  {
    name: "Mountain Climber",
    aliases: [],
    primaryMuscles: ["CORE", "SHOULDERS", "HIP_FLEXORS"],
    secondaryMuscles: ["QUADRICEPS"],
    force: "PULL",
    level: "BEGINNER",
    mechanic: "COMPOUND",
    equipment: ["BODYWEIGHT"],
    category: ["CARDIO", "CORE"],
    instructions: [
      "Start in a high plank position with your hands directly under your shoulders.",
      "Bring one knee toward your chest, keeping your hips low and your core engaged.",
      "Extend that leg back to the starting position and repeat with the other leg."
    ],
    description: "The mountain climber is a dynamic exercise that targets the core, shoulders, and hip flexors while providing a cardiovascular challenge.",
    tips: [
      "Maintain a strong plank position throughout the movement, avoiding sagging or arching your back.",
      "Engage your core and focus on bringing your knees toward your chest with control.",
      "Increase the speed for a more intense cardio workout."
    ]
  },
  {
    name: "Dumbbell Shoulder Press",
    aliases: [],
    primaryMuscles: ["SHOULDERS"],
    secondaryMuscles: ["TRICEPS"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "ISOLATION",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: [
      "Start by holding a dumbbell in each hand at shoulder level, palms facing forward.",
      "Press the dumbbells overhead, fully extending your arms.",
      "Lower the dumbbells back down to shoulder level."
    ],
    description: "The dumbbell shoulder press is an effective exercise for developing shoulder strength and stability.",
    tips: [
      "Maintain a slight bend in your knees and engage your core for stability.",
      "Avoid arching your back or using momentum to lift the weights.",
      "Exhale as you press the dumbbells overhead and inhale as you lower them."
    ]
  },
  {
    name: "Kettlebell Swing",
    aliases: [],
    primaryMuscles: ["GLUTES", "HAMSTRINGS", "BACK"],
    secondaryMuscles: ["CORE", "FOREARMS"],
    force: "PULL",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["KETTLEBELL"],
    category: ["STRENGTH", "CARDIO"],
    instructions: [
      "Stand with your feet slightly wider than shoulder-width apart and the kettlebell on the ground in front of you.",
      "Hinge at the hips and grab the kettlebell with both hands, keeping your back straight.",
      "Drive your hips forward and swing the kettlebell up to chest level, maintaining a strong core and neutral spine.",
      "Let the kettlebell swing back down between your legs and repeat the movement."
    ],
    description: "The kettlebell swing is a dynamic exercise that targets the posterior chain, including the glutes, hamstrings, and back muscles.",
    tips: [
      "Maintain a strong hip hinge and avoid rounding your back.",
      "Use the power generated from your hips and glutes to swing the kettlebell, not your arms.",
      "Start with a lighter weight to practice proper form before progressing to heavier weights."
    ]
  },
  {
    name: "Romanian Deadlift",
    aliases: [],
    primaryMuscles: ["HAMSTRINGS", "GLUTES", "BACK"],
    secondaryMuscles: ["FOREARMS"],
    force: "PULL",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["BARBELL", "DUMBBELL"],
    category: ["STRENGTH"],
    instructions: [
      "Stand with your feet hip-width apart and hold a barbell or dumbbells in front of your thighs with an overhand grip.",
      "Hinge at the hips, keeping your back straight and knees slightly bent.",
      "Lower the weight by moving your hips backward while maintaining a neutral spine.",
      "Feel a stretch in your hamstrings, and then return to the starting position by driving your hips forward."
    ],
    description: "The Romanian deadlift is an exercise that targets the posterior chain, including the hamstrings, glutes, and lower back.",
    tips: [
      "Keep your back straight throughout the movement and avoid rounding your shoulders.",
      "Engage your core and maintain a slight bend in your knees.",
      "Focus on feeling the stretch in your hamstrings as you lower the weight."
    ]
  },
  {
    name: "Barbell Hip Thrust",
    aliases: [],
    primaryMuscles: ["GLUTES"],
    secondaryMuscles: ["HAMSTRINGS"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "ISOLATION",
    equipment: ["BARBELL"],
    category: ["STRENGTH"],
    instructions: [
      "Sit on the ground with your back against a bench, knees bent, and feet flat on the floor.",
      "Place a barbell across your hips, holding it with an overhand grip.",
      "Press through your heels and lift your hips off the ground until your body forms a straight line from your shoulders to your knees.",
      "Squeeze your glutes at the top of the movement, then lower your hips back down and repeat."
    ],
    description: "The barbell hip thrust is a great exercise for targeting and strengthening the glute muscles.",
    tips: [
      "Ensure your feet are planted firmly on the ground throughout the movement.",
      "Maintain a neutral spine and avoid overarching your back.",
      "Start with lighter weights and gradually increase as you become more comfortable with the exercise."
    ]
  },
  {
    name: "Box Jump",
    aliases: [],
    primaryMuscles: ["QUADRICEPS", "GLUTES", "CALVES"],
    secondaryMuscles: ["HAMSTRINGS"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["BOX"],
    category: ["PLYOMETRICS", "POWER"],
    instructions: [
      "Stand facing a sturdy box or platform with your feet shoulder-width apart.",
      "Bend your knees, swing your arms back, and explosively jump onto the box, extending your hips, knees, and ankles.",
      "Land softly on the box with your knees slightly bent.",
      "Step or jump back down and repeat the movement."
    ],
    description: "Box jumps are a plyometric exercise that help improve lower body power, explosiveness, and vertical jumping ability.",
    tips: [
      "Choose a box height that challenges you but allows you to land safely and with proper form.",
      "Engage your core and use your arms to generate momentum during the jump.",
      "Focus on landing softly and absorbing the impact with your leg muscles."
    ]
  },
  {
    name: "Dumbbell Bent-Over Row",
    aliases: [],
    primaryMuscles: ["BACK", "BICEPS"],
    secondaryMuscles: ["REAR_DELTOIDS", "FOREARMS"],
    force: "PULL",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: [
      "Stand with your feet hip-width apart, holding a dumbbell in each hand with your palms facing your body.",
      "Hinge forward at the hips, keeping your back straight and core engaged.",
      "Pull the dumbbells up towards your chest, squeezing your shoulder blades together.",
      "Lower the dumbbells back down with control and repeat the movement."
    ],
    description: "The dumbbell bent-over row is an effective exercise for targeting the muscles of the back and biceps.",
    tips: [
      "Keep your elbows close to your body and avoid shrugging your shoulders.",
      "Maintain a neutral spine and avoid rounding your back.",
      "Engage your core for stability throughout the movement."
    ]
  },
  {
    name: "Jumping Lunges",
    aliases: [],
    primaryMuscles: ["QUADRICEPS", "GLUTES"],
    secondaryMuscles: ["CALVES"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["BODYWEIGHT"],
    category: ["PLYOMETRICS"],
    instructions: [
      "Start in a lunge position with your right foot forward and your knee bent at a 90-degree angle.",
      "Jump explosively, switching your legs mid-air so that your left foot is now forward and your right foot is back.",
      "Land softly in a lunge position and immediately repeat the movement, alternating legs."
    ],
    description: "Jumping lunges are a plyometric exercise that target the lower body muscles, particularly the quadriceps and glutes.",
    tips: [
      "Maintain an upright posture and engage your core for stability.",
      "Land softly on the balls of your feet and immediately transition into the next lunge.",
      "Start with a slower pace and gradually increase speed as you become more comfortable with the exercise."
    ]
  },
  {
    name: "Incline Dumbbell Bench Press",
    aliases: [],
    primaryMuscles: ["UPPER_CHEST", "FRONT_DELTOIDS", "TRICEPS"],
    secondaryMuscles: ["TRAPS"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["DUMBBELL", "BENCH"],
    category: ["STRENGTH"],
    instructions: [
      "Set an incline bench to a 30-45 degree angle.",
      "Hold a dumbbell in each hand and lie back on the bench with your feet flat on the floor.",
      "Position the dumbbells at shoulder level, palms facing forward.",
      "Push the dumbbells upward, extending your arms fully without locking your elbows.",
      "Lower the dumbbells back down to shoulder level and repeat the movement."
    ],
    description: "The incline dumbbell bench press is an effective exercise for targeting the upper chest, front deltoids, and triceps.",
    tips: [
      "Maintain a slight arch in your lower back and keep your shoulder blades retracted.",
      "Exhale as you press the dumbbells up and inhale as you lower them.",
      "Start with lighter weights to ensure proper form and gradually increase as you gain strength."
    ]
  },
  {
    name: "Russian Kettlebell Swing",
    aliases: [],
    primaryMuscles: ["GLUTES", "HAMSTRINGS", "BACK"],
    secondaryMuscles: ["CORE"],
    force: "PULL",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["KETTLEBELL"],
    category: ["STRENGTH", "CARDIO"],
    instructions: [
      "Stand with your feet shoulder-width apart and place a kettlebell between your legs.",
      "Hinge at the hips and grasp the kettlebell with both hands, palms facing inward.",
      "Drive your hips forward and swing the kettlebell up to shoulder level, maintaining a strong core and neutral spine.",
      "Allow the kettlebell to swing back down between your legs and repeat the movement."
    ],
    description: "The Russian kettlebell swing is a dynamic exercise that targets the glutes, hamstrings, and back muscles while providing cardiovascular benefits.",
    tips: [
      "Maintain a strong hip hinge and avoid rounding your back.",
      "Initiate the movement with your hips and use the power generated from your glutes and hamstrings.",
      "Start with a lighter weight to practice proper form before progressing to heavier weights."
    ]
  },
  {
    name: "Overhead Press",
    aliases: [],
    primaryMuscles: ["SHOULDERS"],
    secondaryMuscles: ["TRICEPS"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "ISOLATION",
    equipment: ["BARBELL", "DUMBBELL"],
    category: ["STRENGTH"],
    instructions: [
      "Stand with your feet shoulder-width apart and hold a barbell or dumbbells at shoulder level, palms facing forward.",
      "Press the weight overhead, fully extending your arms.",
      "Lower the weight back down to shoulder level and repeat the movement."
    ],
    description: "The overhead press is a compound exercise that targets the muscles of the shoulders and triceps.",
    tips: [
      "Maintain proper posture throughout the movement, with your core engaged and avoiding excessive arching in the lower back.",
      "Exhale as you press the weight overhead and inhale as you lower it.",
      "Start with lighter weights and gradually increase as you gain strength and confidence in your form."
    ]
  },
  {
    name: "Hanging Leg Raise",
    aliases: [],
    primaryMuscles: ["CORE"],
    secondaryMuscles: ["HIP_FLEXORS"],
    force: "PULL",
    level: "INTERMEDIATE",
    mechanic: "ISOLATION",
    equipment: ["PULL_UP_BAR"],
    category: ["STRENGTH"],
    instructions: [
      "Hang from a pull-up bar with an overhand grip, arms extended and feet off the ground.",
      "Engage your core and raise your legs, bending at the hips and bringing your knees toward your chest.",
      "Pause briefly at the top, then lower your legs back down to the starting position and repeat."
    ],
    description: "The hanging leg raise is an effective exercise for targeting the core muscles, particularly the lower abs.",
    tips: [
      "Maintain a controlled and steady movement, avoiding swinging or using momentum.",
      "Focus on using your core muscles to lift your legs rather than relying on your hip flexors.",
      "If necessary, perform a bent-knee variation by bringing your thighs toward your chest instead of straightening your legs."
    ]
  },
  {
    name: "Step-Up",
    aliases: [],
    primaryMuscles: ["QUADRICEPS", "GLUTES", "HAMSTRINGS"],
    secondaryMuscles: ["CALVES"],
    force: "PUSH",
    level: "BEGINNER",
    mechanic: "COMPOUND",
    equipment: ["BENCH", "STEP"],
    category: ["STRENGTH"],
    instructions: [
      "Stand facing a bench or step with your feet hip-width apart.",
      "Step one foot onto the bench, pressing through your heel to lift your body up.",
      "Extend your hip and knee to bring your other foot up onto the bench.",
      "Step back down with the leading foot, followed by the trailing foot, and repeat on the other side."
    ],
    description: "The step-up is a lower body exercise that targets the quadriceps, glutes, and hamstrings.",
    tips: [
      "Maintain an upright posture and avoid leaning forward or backward.",
      "Focus on driving through the heel of the working leg to engage the glutes.",
      "Choose an appropriate height for the bench or step, considering your comfort and mobility."
    ]
  },
  {
    name: "Plank Jacks",
    aliases: [],
    primaryMuscles: ["CORE"],
    secondaryMuscles: ["SHOULDERS", "HIP_ABDUCTORS"],
    force: "STATIC",
    level: "INTERMEDIATE",
    mechanic: "ISOLATION",
    equipment: ["BODYWEIGHT"],
    category: ["STRENGTH", "CARDIO"],
    instructions: [
      "Start in a high plank position with your hands directly under your shoulders and feet together.",
      "Jump your feet apart, wider than hip-width, while maintaining a strong plank position.",
      "Jump your feet back together, returning to the starting position, and repeat the movement."
    ],
    description: "Plank jacks are a dynamic exercise that target the core muscles while providing a cardiovascular challenge.",
    tips: [
      "Engage your core and keep your hips stable throughout the movement.",
      "Land softly on the balls of your feet during the jumping motion.",
      "Modify the exercise by stepping one foot out at a time instead of jumping if needed."
    ]
  },
  {
    name: "Dumbbell Front Squat",
    aliases: [],
    primaryMuscles: ["QUADRICEPS", "GLUTES"],
    secondaryMuscles: ["CORE"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: [
      "Hold a dumbbell in each hand at shoulder level, palms facing upward.",
      "Stand with your feet shoulder-width apart and toes slightly turned out.",
      "Lower your body into a squat position, keeping your chest up and knees tracking in line with your toes.",
      "Drive through your heels to return to the starting position and repeat the movement."
    ],
    description: "The dumbbell front squat is a variation of the squat exercise that emphasizes the quadriceps and glutes.",
    tips: [
      "Maintain an upright torso throughout the movement, avoiding excessive forward lean.",
      "Engage your core for stability and keep your knees aligned with your toes.",
      "Start with lighter weights to master the technique before progressing to heavier weights."
    ]
  },
  {
    name: "Dumbbell Lateral Raise",
    aliases: [],
    primaryMuscles: ["SHOULDERS"],
    secondaryMuscles: ["TRICEPS"],
    force: "PUSH",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: [
      "Stand with your feet shoulder-width apart and hold a dumbbell in each hand at your sides, palms facing inward.",
      "Raise your arms out to the sides until they are parallel to the floor, keeping your elbows slightly bent.",
      "Pause briefly at the top, then lower the weights back down to the starting position and repeat the movement."
    ],
    description: "The dumbbell lateral raise is an isolation exercise that targets the muscles of the shoulders.",
    tips: [
      "Maintain a slight bend in your elbows throughout the movement.",
      "Avoid swinging or using momentum to lift the weights.",
      "Start with lighter weights and gradually increase as you gain strength and confidence in your form."
    ]
  },
  {
    name: "Dumbbell Bicep Curl",
    aliases: [],
    primaryMuscles: ["BICEPS"],
    secondaryMuscles: ["FOREARMS"],
    force: "PULL",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: [
      "Stand with your feet shoulder-width apart and hold a dumbbell in each hand at your sides, palms facing forward.",
      "Keeping your elbows close to your sides, curl the weights up toward your shoulders.",
      "Pause briefly at the top, then lower the weights back down to the starting position and repeat the movement."
    ],
    description: "The dumbbell bicep curl is an isolation exercise that targets the muscles of the biceps.",
    tips: [
      "Maintain a slight bend in your elbows throughout the movement.",
      "Avoid swinging or using momentum to lift the weights.",
      "Start with lighter weights and gradually increase as you gain strength and confidence in your form."
    ]
  },
  {
    name: "Dumbbell Shoulder Press",
    aliases: [],
    primaryMuscles: ["SHOULDERS"],
    secondaryMuscles: ["TRICEPS"],
    force: "PUSH",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: [
      "Stand with your feet shoulder-width apart and hold a dumbbell in each hand at shoulder level, palms facing forward.",
      "Press the weights overhead until your arms are fully extended.",
      "Pause briefly at the top, then lower the weights back down to the starting position and repeat the movement."
    ],
    description: "The dumbbell shoulder press is an isolation exercise that targets the muscles of the shoulders.",
    tips: [
      "Avoid arching your back or leaning backward during the movement.",
      "Start with lighter weights and gradually increase as you gain strength and confidence in your form."
    ]
  },
  {
    name: "Barbell Squat",
    aliases: [],
    primaryMuscles: ["QUADRICEPS"],
    secondaryMuscles: ["HAMSTRINGS", "GLUTES", "LOWER_BACK"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["BARBELL"],
    category: ["STRENGTH"],
    instructions: ["Position barbell on your shoulders.", "Lower your body until thighs are parallel to the floor.", "Push back up to the starting position."],
    description: "The barbell squat primarily targets the quadriceps, with secondary work on hamstrings, glutes, and lower back. It's a foundational exercise for building leg strength and size.",
    tips: ["Keep your back straight and chest out throughout the motion.", "Do not allow your knees to go beyond your toes."],
  },
  {
    name: "Barbell Deadlift",
    aliases: [],
    primaryMuscles: ["HAMSTRINGS", "LOWER_BACK"],
    secondaryMuscles: ["QUADRICEPS", "GLUTES"],
    force: "PULL",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["BARBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand with feet hip-width apart.", "Bend at the hips and knees to grip the bar.", "Lift the bar by straightening your back and legs."],
    description: "The barbell deadlift is a powerful compound exercise that primarily strengthens the lower back and hamstrings, with secondary work on the quadriceps and glutes.",
    tips: ["Keep your back straight.", "Drive through your heels.", "Avoid rounding your shoulders."],
  },
  {
    name: "Barbell Bench Press",
    aliases: [],
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["TRICEPS", "SHOULDERS"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["BARBELL", "BENCH"],
    category: ["STRENGTH"],
    instructions: ["Lie on a bench with feet planted on the ground.", "Hold the barbell above your chest.", "Lower the bar to your chest, then push it back up."],
    description: "The barbell bench press is a staple chest exercise that also works the triceps and shoulders. It's widely used for building upper body strength and size.",
    tips: ["Don't bounce the bar off your chest.", "Keep your wrists straight.", "Control the weight on the way down."],
  },
  {
    name: "Barbell Row",
    aliases: [],
    primaryMuscles: ["MIDDLE_BACK"],
    secondaryMuscles: ["BICEPS", "SHOULDERS"],
    force: "PULL",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["BARBELL"],
    category: ["STRENGTH"],
    instructions: ["Bend your knees slightly and bring your torso forward.", "Keep the back straight and pull the bar towards your torso.", "Lower the bar to return to the starting position."],
    description: "The barbell row is a compound exercise that primarily targets the middle back, while also working the biceps and shoulders.",
    tips: ["Keep your back straight.", "Avoid using your body momentum to lift the weights."],
  },
  {
    name: "Barbell Overhead Press",
    aliases: [],
    primaryMuscles: ["SHOULDERS"],
    secondaryMuscles: ["TRICEPS"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["BARBELL"],
    category: ["STRENGTH"],
    instructions: ["Hold the barbell at shoulder level.", "Extend your arms to push the barbell overhead.", "Lower the barbell back to shoulder level."],
    description: "The barbell overhead press is a compound movement that primarily targets the shoulders and also works the triceps. It's fundamental for building upper body strength.",
    tips: ["Keep your back straight.", "Avoid arching your back.", "Control the movement on the way down."],
  },
  {
    name: "Barbell Curl",
    aliases: [],
    primaryMuscles: ["BICEPS"],
    secondaryMuscles: [],
    force: "PULL",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["BARBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand up straight with a barbell in your hands at arm's length.", "Curl the weights while contracting your biceps.", "Slowly return to the starting position."],
    description: "The barbell curl is a classic arm exercise that primarily targets the biceps.",
    tips: ["Keep your elbows close to your torso.", "Do not use your back or shoulders to lift the weights."],
  },
  {
    name: "Barbell Tricep Extension",
    aliases: [],
    primaryMuscles: ["TRICEPS"],
    secondaryMuscles: [],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "ISOLATION",
    equipment: ["BARBELL", "BENCH"],
    category: ["STRENGTH"],
    instructions: ["Lie on a bench and hold a barbell with hands shoulder-width apart.", "Extend your arms fully.", "Lower the bar by bending your elbows until it's about an inch from your forehead."],
    description: "The barbell tricep extension, also known as skullcrusher, is an isolation movement targeting the triceps.",
    tips: ["Keep your elbows in the same spot.", "Avoid using your back or shoulders to push the weight."],
  },
  {
    name: "Barbell Lunges",
    aliases: [],
    primaryMuscles: ["QUADRICEPS"],
    secondaryMuscles: ["GLUTES", "HAMSTRINGS"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["BARBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand straight with a barbell placed on your shoulders.", "Step forward with one foot until your leg reaches a 90-degree angle.", "Push up through your heel to return to the starting position."],
    description: "Barbell lunges are a compound movement that primarily target the quadriceps, but also work the glutes and hamstrings.",
    tips: ["Keep your torso upright throughout the movement.", "Avoid letting your knee pass your toes on the forward step."],
  },
  {
    name: "Barbell Hip Thrust",
    aliases: [],
    primaryMuscles: ["GLUTES"],
    secondaryMuscles: ["HAMSTRINGS"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["BARBELL", "BENCH"],
    category: ["STRENGTH"],
    instructions: ["Position your back against a bench, and have a loaded barbell over your hips.", "Thrust your hips upward, keeping your back straight.", "Lower your hips until your butt hovers above the floor."],
    description: "The barbell hip thrust is a compound exercise that primarily targets the glutes and also works the hamstrings.",
    tips: ["Keep your back straight and chin tucked.", "Avoid hyperextending your back at the top of the movement."],
  },
  {
    name: "Barbell Romanian Deadlift",
    aliases: [],
    primaryMuscles: ["HAMSTRINGS"],
    secondaryMuscles: ["LOWER_BACK", "GLUTES"],
    force: "PULL",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["BARBELL"],
    category: ["STRENGTH"],
    instructions: ["Hold a barbell at hip level.", "Lower the barbell while keeping it close to your body, bending at the hips and keeping your back straight.", "Return to the upright position."],
    description: "The Barbell Romanian Deadlift is a compound exercise that targets the hamstrings and also works the lower back and glutes.",
    tips: ["Keep your back straight.", "Avoid rounding your back.", "Drive the movement with your hips."],
  },
  {
    name: "Barbell Shoulder Press",
    aliases: [],
    primaryMuscles: ["SHOULDERS"],
    secondaryMuscles: ["TRICEPS"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["BARBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand with your feet shoulder-width apart. Hold the barbell at shoulder level with your hands shoulder-width apart.", "Extend your arms fully, raising the barbell above your head.", "Lower the barbell back to shoulder level."],
    description: "The Barbell Shoulder Press is a compound movement that primarily targets the shoulders and also works the triceps. It is a fundamental exercise for building upper body strength.",
    tips: ["Keep your back straight.", "Avoid arching your back.", "Control the movement on the way down."],
  },
  {
    name: "Barbell Shrug",
    aliases: [],
    primaryMuscles: ["TRAPS"],
    secondaryMuscles: [],
    force: "PULL",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["BARBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand up straight with a barbell in front of you.", "Lift the barbell by raising your shoulders as high as possible.", "Lower your shoulders to return to the starting position."],
    description: "Barbell shrugs primarily target the trapezius muscles in the upper back and neck, aiding in the development of strong, broad shoulders.",
    tips: ["Keep your arms straight throughout the movement.", "Avoid rolling your shoulders."],
  },
  {
    name: "Barbell Upright Row",
    aliases: [],
    primaryMuscles: ["SHOULDERS"],
    secondaryMuscles: ["TRAPS"],
    force: "PULL",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["BARBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand up straight and hold a barbell at the mid portion of your thighs.", "Lift the barbell straight up while keeping it close to your body.", "Lower the barbell back down slowly to the starting position."],
    description: "The barbell upright row is a compound exercise that primarily targets the shoulders and the trapezius muscles in the upper back and neck.",
    tips: ["Keep your body and wrists straight.", "Do not use your body to lift the weight."],
  },
  {
    name: "Barbell Front Raise",
    aliases: [],
    primaryMuscles: ["SHOULDERS"],
    secondaryMuscles: [],
    force: "PUSH",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["BARBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand with your feet shoulder-width apart, holding a barbell at your thighs.", "Keep your arms straight and lift the barbell in front of you until it reaches shoulder level.", "Lower the barbell back to the starting position."],
    description: "Barbell front raises primarily target the shoulders and are crucial for improving shoulder strength and stability.",
    tips: ["Keep your back straight and core engaged.", "Avoid using momentum to raise the barbell."],
  },
  {
    name: "Barbell Calf Raise",
    aliases: [],
    primaryMuscles: ["CALF_MUSCLES"],
    secondaryMuscles: [],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "ISOLATION",
    equipment: ["BARBELL"],
    category: ["STRENGTH"],
    instructions: ["Place a barbell across your upper back and stand with your feet hip-width apart.", "Raise your body upward by extending your ankles as high as possible.", "Lower your heels by bending your ankles until your calves are stretched."],
    description: "Barbell calf raises are an isolation exercise that targets the calf muscles, improving both strength and muscle definition.",
    tips: ["Keep your core engaged and back straight.", "Control the movement on the way down."],
  },
  {
    name: "Dumbbell Squat",
    aliases: [],
    primaryMuscles: ["QUADRICEPS"],
    secondaryMuscles: ["GLUTES", "HAMSTRINGS"],
    force: "PUSH",
    level: "BEGINNER",
    mechanic: "COMPOUND",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand with feet hip-width apart holding dumbbells at your sides.", "Lower your body by bending your knees and hips.", "Stand back up to return to the starting position."],
    description: "The dumbbell squat targets the quadriceps and also works the glutes and hamstrings. It's a versatile exercise that can be done anywhere with a pair of dumbbells.",
    tips: ["Keep your back straight and chest up.", "Do not let your knees go beyond your toes."],
  },
  {
    name: "Dumbbell Deadlift",
    aliases: [],
    primaryMuscles: ["HAMSTRINGS"],
    secondaryMuscles: ["GLUTES", "LOWER_BACK"],
    force: "PULL",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand holding dumbbells at your sides.", "Lower the dumbbells by bending at your hips and knees.", "Stand up straight to return to the starting position."],
    description: "The dumbbell deadlift primarily targets the hamstrings and also works the glutes and lower back. This is an essential exercise for developing overall body strength and stability.",
    tips: ["Keep your back straight.", "Avoid rounding your back.", "Drive the movement with your hips."],
  },
  {
    name: "Dumbbell Bench Press",
    aliases: [],
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["TRICEPS", "SHOULDERS"],
    force: "PUSH",
    level: "BEGINNER",
    mechanic: "COMPOUND",
    equipment: ["DUMBBELL", "BENCH"],
    category: ["STRENGTH"],
    instructions: ["Lie on a bench holding dumbbells at your shoulders.", "Press the dumbbells up until your arms are straight.", "Lower the dumbbells back to the starting position."],
    description: "The dumbbell bench press primarily targets the chest and also works the triceps and shoulders. It's a versatile exercise that can improve upper body strength and stability.",
    tips: ["Keep your feet flat on the floor.", "Avoid arching your back."],
  },
  {
    name: "Dumbbell Row",
    aliases: [],
    primaryMuscles: ["MIDDLE_BACK"],
    secondaryMuscles: ["BICEPS", "SHOULDERS"],
    force: "PULL",
    level: "BEGINNER",
    mechanic: "COMPOUND",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand with a dumbbell in one hand, hinging at the waist and keeping your back straight.", "Pull the dumbbell up to your chest, keeping your elbow close to your body.", "Lower the dumbbell back down."],
    description: "The dumbbell row targets the middle back while also working the biceps and shoulders. This is a great exercise for improving back strength and posture.",
    tips: ["Keep your back straight and core engaged.", "Avoid twisting your torso during the exercise."],
  },
  {
    name: "Dumbbell Overhead Press",
    aliases: [],
    primaryMuscles: ["SHOULDERS"],
    secondaryMuscles: ["TRICEPS"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand with feet hip-width apart, holding dumbbells at shoulder level.", "Extend your arms to push the dumbbells overhead.", "Lower the dumbbells back to shoulder level."],
    description: "The dumbbell overhead press is a compound exercise that targets the shoulders and also works the triceps. This is an essential movement for improving upper body strength and stability.",
    tips: ["Keep your back straight and core engaged.", "Avoid arching your back.", "Control the movement on the way down."],
  },
  {
    name: "Dumbbell Curl",
    aliases: [],
    primaryMuscles: ["BICEPS"],
    secondaryMuscles: [],
    force: "PULL",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand with feet hip-width apart, holding dumbbells at your sides.", "Bend your elbows to curl the dumbbells towards your shoulders.", "Lower the dumbbells back down to your sides."],
    description: "The dumbbell curl is an isolation exercise that specifically targets the biceps. This is a simple yet effective movement for improving arm strength and size.",
    tips: ["Keep your elbows close to your body.", "Avoid swinging the dumbbells or using your body momentum."],
  },
  {
    name: "Dumbbell Tricep Extension",
    aliases: [],
    primaryMuscles: ["TRICEPS"],
    secondaryMuscles: [],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "ISOLATION",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand or sit while holding a dumbbell with both hands.", "Raise the dumbbell over your head, keeping your elbows close to your head.", "Lower the dumbbell by bending at your elbows.", "Raise the dumbbell back up by extending your elbows."],
    description: "The dumbbell tricep extension is an isolation exercise that targets the triceps. It's an effective movement for improving arm strength and tone.",
    tips: ["Keep your elbows close to your head.", "Avoid using your body momentum to lift the dumbbell."],
  },
  {
    name: "Dumbbell Lunges",
    aliases: [],
    primaryMuscles: ["QUADRICEPS", "GLUTES"],
    secondaryMuscles: ["HAMSTRINGS"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand upright with a dumbbell in each hand.", "Step forward with one foot and lower your body by bending your knees.", "Push up and back to the starting position, then repeat with the other leg."],
    description: "Dumbbell lunges are a compound exercise that target the quadriceps and glutes while also working the hamstrings. They are effective for building lower body strength and stability.",
    tips: ["Keep your front knee directly over your ankle during the lunge.", "Maintain a straight back and engaged core.", "Avoid letting your back knee touch the ground."],
  },
  {
    name: "Dumbbell Step-Up",
    aliases: [],
    primaryMuscles: ["QUADRICEPS", "GLUTES"],
    secondaryMuscles: ["HAMSTRINGS"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "COMPOUND",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand in front of a step or bench while holding a dumbbell in each hand.", "Step up onto the step with one foot, pressing through your heel.", "Bring your other foot up to join it.", "Step back down and repeat."],
    description: "Dumbbell step-ups target the quadriceps and glutes, while also working the hamstrings. This exercise is effective for building lower body strength and improving balance and coordination.",
    tips: ["Keep your chest lifted and your back straight.", "Press through your heel as you step up.", "Do not rush the movement. Maintain control at all times."],
  },
  {
    name: "Dumbbell Calf Raise",
    aliases: [],
    primaryMuscles: ["CALF_MUSCLES"],
    secondaryMuscles: [],
    force: "PUSH",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand upright holding a dumbbell in each hand.", "Raise your heels off the floor while keeping your knees straight.", "Lower your heels back down and repeat."],
    description: "The dumbbell calf raise specifically targets the calf muscles. It's a simple yet effective exercise for improving lower leg strength and definition.",
    tips: ["Keep your body upright.", "Raise your heels as high as possible.", "Avoid bending your knees during the exercise."],
  },
  {
    name: "Dumbbell Flyes",
    aliases: [],
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["SHOULDERS"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "ISOLATION",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: ["Lie on a bench with a dumbbell in each hand, palms facing each other.", "With a slight bend at the elbows, lower your arms out at both sides in a wide arc until you feel a stretch in your chest.", "Return your arms back to the starting position as if you were 'hugging' a large tree."],
    description: "Dumbbell flyes primarily target the chest muscles, with secondary emphasis on the shoulders. This isolation exercise is effective for enhancing chest strength and appearance.",
    tips: ["Keep a slight bend in your elbows throughout the exercise.", "Avoid using your body momentum or arching your back.", "Focus on using your chest muscles to bring the dumbbells back up."],
  },
  {
    name: "Dumbbell Reverse Flyes",
    aliases: [],
    primaryMuscles: ["REAR_DELTOIDS", "MIDDLE_BACK"],
    secondaryMuscles: ["SHOULDERS"],
    force: "PULL",
    level: "INTERMEDIATE",
    mechanic: "ISOLATION",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: ["Hold a dumbbell in each hand and bend over at your waist.", "With your elbows slightly bent, raise the dumbbells to your side until your arms are parallel to the floor.", "Lower the dumbbells back down and repeat."],
    description: "Dumbbell reverse flyes primarily target the rear deltoids and the middle back. This exercise can improve shoulder balance and posture.",
    tips: ["Keep your back straight and avoid rounding your shoulders.", "Focus on squeezing your shoulder blades together at the top of the movement.", "Control the dumbbells on the way down."],
  },
  {
    name: "Dumbbell Hammer Curl",
    aliases: [],
    primaryMuscles: ["BICEPS", "BRACHIALIS"],
    secondaryMuscles: ["FOREARMS"],
    force: "PULL",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand up with a dumbbell in each hand, arms fully extended, and palms facing your torso.", "Keep your elbows close to your torso at all times.", "Curl the weights while contracting your biceps as you breathe out. Only the forearms should move."],
    description: "Dumbbell hammer curls primarily target the biceps and the brachialis (a muscle of the upper arm), with secondary benefits to the forearms. This exercise helps improve both arm strength and appearance.",
    tips: ["Avoid using your back or shoulders to lift the weights; your forearms should do all the work.", "Perform the exercise slowly, focusing on the muscle contraction and not on the weights you are lifting."],
  },
  {
    name: "Dumbbell Tricep Kickback",
    aliases: [],
    primaryMuscles: ["TRICEPS"],
    secondaryMuscles: [],
    force: "PUSH",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: ["Start with a dumbbell in each hand and your palms facing your torso.", "Keep your back straight with a slight bend in the knees and bend forward at the waist. Your torso should be almost parallel to the floor.", "Now lift the weights to your side as you exhale, keeping your forearms perpendicular to the floor."],
    description: "The dumbbell tricep kickback primarily targets the triceps. It's an effective exercise for isolating this muscle group and enhancing arm strength.",
    tips: ["Keep your upper arms stationary; only the forearms should move.", "Use your triceps to lift the weights as you exhale, not your back or shoulders."],
  },
  {
    name: "Dumbbell Side Lateral Raise",
    aliases: [],
    primaryMuscles: ["SHOULDERS"],
    secondaryMuscles: ["UPPER_BACK"],
    force: "PUSH",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand upright with a dumbbell in each hand at arm's length. Keep your elbows close to your torso.", "Keeping your torso stationary, lift the dumbbells to your side with a slight bend on the elbow.", "Lower the dumbbells back down slowly to the starting position."],
    description: "The dumbbell side lateral raise primarily targets the shoulder muscles. It's a great exercise for building shoulder width and improving upper body strength.",
    tips: ["Keep your back straight and avoid using your body momentum to lift the weights.", "Control the weights on the way down."],
  },
  {
    name: "Dumbbell Front Raise",
    aliases: [],
    primaryMuscles: ["SHOULDERS"],
    secondaryMuscles: ["UPPER_BACK"],
    force: "PUSH",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["DUMBBELL"],
    category: ["STRENGTH"],
    instructions: ["Stand upright with a dumbbell in each hand at arm's length. The elbows should be close to the torso.", "While keeping your torso stationary, lift the dumbbells in front of you with a slight bend at the elbow.", "Lower the dumbbells back down slowly to the starting position."],
    description: "The dumbbell front raise primarily targets the shoulder muscles. It's an effective exercise for increasing shoulder strength and flexibility.",
    tips: ["Keep your back straight and avoid using your body momentum to lift the weights.", "Control the weights on the way down."],
  },
  {
    name: "Cable Flyes",
    aliases: [],
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["SHOULDERS", "TRICEPS"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "ISOLATION",
    equipment: ["CABLE"],
    category: ["STRENGTH"],
    instructions: ["Stand in the middle of a cable cross setup with handles in each hand.", "With a slight bend in your elbows, extend your arms out to your sides.", "Pull your hands together in front of your body.", "Reverse the motion, controlling the cables as they return to the starting position."],
    description: "Cable flyes primarily target the chest muscles, with secondary emphasis on the shoulders and triceps. This exercise is great for shaping and strengthening the chest.",
    tips: ["Keep a slight bend in your elbows during the exercise.", "Avoid letting the weights control you on the way back; maintain control of the movement."],
  },
  {
    name: "Cable Row",
    aliases: [],
    primaryMuscles: ["BACK"],
    secondaryMuscles: ["BICEPS", "SHOULDERS"],
    force: "PULL",
    level: "BEGINNER",
    mechanic: "COMPOUND",
    equipment: ["CABLE"],
    category: ["STRENGTH"],
    instructions: ["Sit at a low pulley cable station with a V-bar handle attachment.", "Pull back until your torso is at a 90-degree angle from your legs, with your back slightly arched and chest sticking out.", "Pull the handles towards your waist while keeping your body stationary.", "Return to the initial position while controlling the resistance."],
    description: "Cable rows are mainly focused on the back, while also working the biceps and shoulders. It's a fantastic exercise for developing the thickness of the back muscles.",
    tips: ["Avoid using your torso for momentum during the lift.", "Focus on squeezing your back muscles when pulling the handles."],
  },
  {
    name: "Cable Lat Pulldown",
    aliases: [],
    primaryMuscles: ["LATS"],
    secondaryMuscles: ["BICEPS", "MIDDLE_BACK"],
    force: "PULL",
    level: "BEGINNER",
    mechanic: "COMPOUND",
    equipment: ["CABLE"],
    category: ["STRENGTH"],
    instructions: ["Sit down at a lat pulldown station and grab the bar with an overhand grip.", "Pull the bar down in front of you to about collarbone level while keeping your torso stationary.", "Reverse the motion, controlling the cable as it returns to the starting position."],
    description: "The cable lat pulldown is a great exercise for developing the latissimus dorsi muscle of the back. It also works the biceps and muscles in the middle of the back.",
    tips: ["Keep your back straight and chest lifted during the exercise.", "Avoid using your body momentum to pull the bar down; focus on using your back muscles."],
  },
  {
    name: "Cable Crossover",
    aliases: [],
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["SHOULDERS", "TRICEPS"],
    force: "PUSH",
    level: "INTERMEDIATE",
    mechanic: "ISOLATION",
    equipment: ["CABLE"],
    category: ["STRENGTH"],
    instructions: ["Stand in the middle of a cable cross setup with handles in each hand.", "With a slight bend in your elbows, extend your arms out to your sides.", "Pull your hands together in front of your body.", "Reverse the motion, controlling the cables as they return to the starting position."],
    description: "Cable crossovers are an excellent exercise for isolating the chest muscles while also working the shoulders and triceps. It's a popular choice for building and shaping the chest muscles.",
    tips: ["Keep a slight bend in your elbows during the exercise.", "Avoid letting the weights control you on the way back; maintain control of the movement."],
  },
  {
    name: "Cable Bicep Curl",
    aliases: [],
    primaryMuscles: ["BICEPS"],
    secondaryMuscles: ["FOREARMS"],
    force: "PULL",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["CABLE"],
    category: ["STRENGTH"],
    instructions: ["Stand in front of a low pulley cable station with a straight bar attachment.", "Grab the bar with an underhand grip and keep your elbows close to your torso.", "Curl the bar up towards your chest while keeping your upper arms stationary.", "Lower the bar back down slowly to the starting position."],
    description: "Cable bicep curls are a great exercise for isolating the biceps. It's a popular choice for building and shaping the biceps.",
    tips: ["Keep your elbows close to your torso during the exercise.", "Avoid using your body momentum to curl the bar up; focus on using your biceps."],
  },
  {
    name: "Cable Tricep Pushdown",
    aliases: [],
    primaryMuscles: ["TRICEPS"],
    secondaryMuscles: ["SHOULDERS"],
    force: "PUSH",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["CABLE"],
    category: ["STRENGTH"],
    instructions: ["Stand in front of a high pulley cable station with a straight bar attachment.", "Grab the bar with an overhand grip and keep your elbows close to your torso.", "Push the bar down towards your thighs while keeping your upper arms stationary.", "Return the bar back up slowly to the starting position."],
    description: "Cable tricep pushdowns are a great exercise for isolating the triceps. It's a popular choice for building and shaping the triceps.",
    tips: ["Keep your elbows close to your torso during the exercise.", "Avoid using your body momentum to push the bar down; focus on using your triceps."],
  },
  {
    name: "Cable Crunch",
    aliases: [],
    primaryMuscles: ["ABS"],
    secondaryMuscles: [],
    force: "PULL",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["CABLE"],
    category: ["STRENGTH"],
    instructions: ["Kneel below a high pulley cable station with a rope attachment.", "Grab the rope with both hands and place it behind your head.", "Pull the rope down towards your knees while keeping your hips stationary.", "Return the rope back up slowly to the starting position."],
    description: "Cable crunches are a great exercise for isolating the abdominal muscles. It's a popular choice for building and shaping the abs.",
    tips: ["Keep your hips stationary during the exercise.", "Avoid using your body momentum to pull the rope down; focus on using your abs."],
  },
  {
    name: "Cable Side Lateral Raise",
    aliases: [],
    primaryMuscles: ["SHOULDERS"],
    secondaryMuscles: ["TRAPS"],
    force: "PUSH",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["CABLE"],
    category: ["STRENGTH"],
    instructions: ["Stand in front of a low pulley cable station with a D-handle attachment.", "Grab the handle with one hand and place it in front of your opposite hip.", "Raise the handle up to shoulder level while keeping your arm straight.", "Return the handle back down slowly to the starting position."],
    description: "Cable side lateral raises are a great exercise for isolating the side deltoid muscles. It's a popular choice for building and shaping the shoulders.",
    tips: ["Keep your arm straight during the exercise.", "Avoid using your body momentum to raise the handle up; focus on using your shoulders."],
  },
  {
    name: "Cable Front Raise",
    aliases: [],
    primaryMuscles: ["SHOULDERS"],
    secondaryMuscles: ["TRAPS"],
    force: "PUSH",
    level: "BEGINNER",
    mechanic: "ISOLATION",
    equipment: ["CABLE"],
    category: ["STRENGTH"],
    instructions: ["Stand in front of a low pulley cable station with a D-handle attachment.", "Grab the handle with one hand and place it in front of your opposite hip.", "Raise the handle up to shoulder level while keeping your arm straight.", "Return the handle back down slowly to the starting position."],
    description: "Cable front raises are a great exercise for isolating the front deltoid muscles. It's a popular choice for building and shaping the shoulders.",
    tips: ["Keep your arm straight during the exercise.", "Avoid using your body momentum to raise the handle up; focus on using your shoulders."],
  }
];

export default seedData;

