import { Mood } from "@prisma/client";

export const MOODS = [
  { name: Mood.AFFECTION, value: Mood.AFFECTION, color: "bg-pink-400 dark:bg-pink-600 text-white", tags: ["love", "warmth"], icon: "❤️" },
  { name: Mood.AGITATION, value: Mood.AGITATION, color: "bg-orange-400 dark:bg-orange-600 text-black", tags: ["nervousness", "anxiety", "agitated"], icon: "😤" },
  { name: Mood.AMUSEMENT, value: Mood.AMUSEMENT, color: "bg-yellow-400 dark:bg-yellow-600 text-black", tags: ["joy", "fun", "amused"], icon: "😄", },
  { name: Mood.ANGER, value: Mood.ANGER, color: "bg-red-400 dark:bg-red-600 text-white", tags: ["rage", "fury", "angry",], icon: "😡", },
  { name: Mood.ANNOYANCE, value: Mood.ANNOYANCE, color: "bg-orange-400 dark:bg-orange-600 text-black", tags: ["irritation", "bother", "annoyed"], icon: "😒", },
  { name: Mood.ANXIETY, value: Mood.ANXIETY, color: "bg-blue-400 dark:bg-blue-600 text-black", tags: ["worry", "nervousness", "anxious",], icon: "😰", },
  { name: Mood.APATHY, value: Mood.APATHY, color: "bg-gray-400 dark:bg-gray-600 text-black", tags: ["indifference", "disinterest"], icon: "😑" },
  { name: Mood.AWE, value: Mood.AWE, color: "bg-green-400 dark:bg-green-600 text-black", tags: ["wonder", "amazement"], icon: "😲", },
  { name: Mood.BOREDOM, value: Mood.BOREDOM, color: "bg-gray-400 dark:bg-gray-600 text-black", tags: ["disinterest", "ennui"], icon: "😴", },
  { name: Mood.CALM, value: Mood.CALM, color: "bg-teal-400 dark:bg-teal-600 text-black", tags: ["peace", "relaxation"], icon: "😌", },
  { name: Mood.CONFUSION, value: Mood.CONFUSION, color: "bg-purple-400 dark:bg-purple-600 text-white", tags: ["bewilderment", "muddle"], icon: "😵", },
  { name: Mood.CONTEMPT, value: Mood.CONTEMPT, color: "bg-indigo-400 dark:bg-indigo-600 text-white", tags: ["disdain", "scorn"], icon: "😒", },
  { name: Mood.CURIOSITY, value: Mood.CURIOSITY, color: "bg-yellow-400 dark:bg-yellow-600 text-black", tags: ["interest", "inquiry"], icon: "🤔", },
  { name: Mood.DEPRESSION, value: Mood.DEPRESSION, color: "bg-black dark:bg-gray-800 text-white", tags: ["sadness", "hopelessness"], icon: "😔", },
  { name: Mood.DESIRE, value: Mood.DESIRE, color: "bg-red-400 dark:bg-red-600 text-white", tags: ["want", "longing"], icon: "❤️", },
  { name: Mood.DESPAIR, value: Mood.DESPAIR, color: "bg-gray-600 dark:bg-gray-800 text-white", tags: ["hopelessness", "anguish"], icon: "😞" },
  { name: Mood.DISAPPOINTMENT, value: Mood.DISAPPOINTMENT, color: "bg-gray-600 dark:bg-gray-800 text-white", tags: ["letdown", "dismay"], icon: "😞", },
  { name: Mood.DISGUST, value: Mood.DISGUST, color: "bg-purple-400 dark:bg-purple-600 text-white", tags: ["repulsion", "aversion"], icon: "🤢" },
  { name: Mood.DOUBT, value: Mood.DOUBT, color: "bg-yellow-400 dark:bg-yellow-600 text-black", tags: ["uncertainty", "skepticism"], icon: "🤔" },
  { name: Mood.EAGERNESS, value: Mood.EAGERNESS, color: "bg-green-400 dark:bg-green-600 text-black", tags: ["enthusiasm", "readiness"], icon: "😃" },
  { name: Mood.EMBARRASSMENT, value: Mood.EMBARRASSMENT, color: "bg-red-400 dark:bg-red-600 text-black", tags: ["shame", "blush"], icon: "😳" },
  { name: Mood.ENVY, value: Mood.ENVY, color: "bg-green-400 dark:bg-green-600 text-black", tags: ["jealousy", "covetousness"], icon: "😒", },
  { name: Mood.EXCITEMENT, value: Mood.EXCITEMENT, color: "bg-yellow-400 dark:bg-yellow-600 text-black", tags: ["thrill", "enthusiasm"], icon: "😆" },
  { name: Mood.FEAR, value: Mood.FEAR, color: "bg-gray-400 dark:bg-gray-600 text-black", tags: ["terror", "fright"], icon: "😨" },
  { name: Mood.FRUSTRATION, value: Mood.FRUSTRATION, color: "bg-red-400 dark:bg-red-600 text-white", tags: ["irritation", "agitation"], icon: "😤" },
  { name: Mood.GRATITUDE, value: Mood.GRATITUDE, color: "bg-green-400 dark:bg-green-600 text-black", tags: ["thankfulness", "appreciation"], icon: "🙏" },
  { name: Mood.GRIEF, value: Mood.GRIEF, color: "bg-blue-400 dark:bg-blue-600 text-white", tags: ["sorrow", "heartbreak"], icon: "😢" },
  { name: Mood.GUILT, value: Mood.GUILT, color: "bg-orange-400 dark:bg-orange-600 text-black", tags: ["remorse", "regret"], icon: "😖" },
  { name: Mood.HAPPINESS, value: Mood.HAPPINESS, color: "bg-yellow-400 dark:bg-yellow-600 text-black", tags: ["joy", "contentment", "happy"], icon: "😀" },
  { name: Mood.HATRED, value: Mood.HATRED, color: "bg-red-900 dark:bg-red-700 text-white", tags: ["loathing", "detest"], icon: "😠", },
  { name: Mood.HOPE, value: Mood.HOPE, color: "bg-yellow-400 dark:bg-yellow-600 text-black", tags: ["optimism", "expectation"], icon: "🌞" },
  { name: Mood.HOSTILITY, value: Mood.HOSTILITY, color: "bg-red-900 dark:bg-red-700 text-white", tags: ["aggression", "antagonism"], icon: "😠" },
  { name: Mood.HUMILIATION, value: Mood.HUMILIATION, color: "bg-red-400 dark:bg-red-600 text-black", tags: ["disgrace", "embarrassment"], icon: "😳" },
  { name: Mood.INTEREST, value: Mood.INTEREST, color: "bg-blue-400 dark:bg-blue-700 text-black", tags: ["curiosity", "attention"], icon: "🧐" },
  { name: Mood.JEALOUSY, value: Mood.JEALOUSY, color: "bg-orange-400 dark:bg-orange-600 text-black", tags: ["envy", "resentment"], icon: "😒" },
  { name: Mood.JOY, value: Mood.JOY, color: "bg-yellow-400 dark:bg-yellow-600 text-black", tags: ["happiness", "elation"], icon: "😄" },
  { name: Mood.LONELINESS, value: Mood.LONELINESS, color: "bg-gray-400 dark:bg-gray-600 text-black", tags: ["isolation", "solitude"], icon: "😔" },
  { name: Mood.LOVE, value: Mood.LOVE, color: "bg-red-400 dark:bg-red-600 text-white", tags: ["affection", "romance"], icon: "❤️" },
  { name: Mood.NERVOUSNESS, value: Mood.NERVOUSNESS, color: "bg-blue-400 dark:bg-blue-600 text-black", tags: ["anxiety", "jitters"], icon: "😰" },
  { name: Mood.OPTIMISM, value: Mood.OPTIMISM, color: "bg-green-400 dark:bg-green-600 text-black", tags: ["hope", "positivity"], icon: "😃" },
  { name: Mood.OUTRAGE, value: Mood.OUTRAGE, color: "bg-red-400 dark:bg-red-600 text-white", tags: ["anger", "indignation"], icon: "😡" },
  { name: Mood.PANIC, value: Mood.PANIC, color: "bg-gray-400 dark:bg-gray-600 text-black", tags: ["terror", "fear"], icon: "😨" },
  { name: Mood.PASSION, value: Mood.PASSION, color: "bg-red-400 dark:bg-red-600 text-white", tags: ["desire", "lust"], icon: "😍" },
  { name: Mood.PITY, value: Mood.PITY, color: "bg-blue-400 dark:bg-blue-600 text-black", tags: ["compassion", "empathy"], icon: "😢" },
  { name: Mood.PRIDE, value: Mood.PRIDE, color: "bg-purple-400 dark:bg-purple-600 text-white", tags: ["self-esteem", "arrogance", "cocky"], icon: "😏" },
  { name: Mood.RELIEF, value: Mood.RELIEF, color: "bg-teal-400 dark:bg-teal-600 text-black", tags: ["ease", "comfort"], icon: "😌" },
  { name: Mood.REMORSE, value: Mood.REMORSE, color: "bg-orange-400 dark:bg-orange-600 text-black", tags: ["regret", "guilt"], icon: "😔", },
  { name: Mood.RESIGNATION, value: Mood.RESIGNATION, color: "bg-gray-400 dark:bg-gray-600 text-black", tags: ["acceptance", "surrender"], icon: "😔", },
  { name: Mood.SADNESS, value: Mood.SADNESS, color: "bg-blue-400 dark:bg-blue-600 text-white", tags: ["sorrow", "unhappiness"], icon: "😞" },
  { name: Mood.SATISFACTION, value: Mood.SATISFACTION, color: "bg-teal-400 dark:bg-teal-600 text-black", tags: ["contentment", "pleasure"], icon: "😌" },
  { name: Mood.SHAME, value: Mood.SHAME, color: "bg-red-400 dark:bg-red-600 text-black", tags: ["embarrassment", "humiliation"], icon: "😳" },
  { name: Mood.SHOCK, value: Mood.SHOCK, color: "bg-gray-400 dark:bg-gray-600 text-black", tags: ["surprise", "dismay"], icon: "😲" },
  { name: Mood.SORROW, value: Mood.SORROW, color: "bg-blue-400 dark:bg-blue-600 text-white", tags: ["sadness", "grief"], icon: "😢" },
  { name: Mood.SURPRISE, value: Mood.SURPRISE, color: "bg-green-400 dark:bg-green-600 text-black", tags: ["shock", "astonishment"], icon: "😲" },
  { name: Mood.SYMPATHY, value: Mood.SYMPATHY, color: "bg-blue-400 dark:bg-blue-600 text-black", tags: ["compassion", "pity"], icon: "😢" },
  { name: Mood.TERROR, value: Mood.TERROR, color: "bg-gray-400 dark:bg-gray-600 text-black", tags: ["fear", "horror"], icon: "😨" },
  { name: Mood.TRUST, value: Mood.TRUST, color: "bg-green-400 dark:bg-green-600 text-black", tags: ["faith", "confidence"], icon: "🤝" },
  { name: Mood.WONDER, value: Mood.WONDER, color: "bg-green-400 dark:bg-green-600 text-black", tags: ["awe", "amazement"], icon: "😲" },
  { name: Mood.WORRY, value: Mood.WORRY, color: "bg-blue-400 dark:bg-blue-600 text-black", tags: ["anxiety", "concern"], icon: "😰" },
  { name: Mood.ZEAL, value: Mood.ZEAL, color: "bg-yellow-400 dark:bg-yellow-600 text-black", tags: ["enthusiasm", "passion"], icon: "😃" }
]
